### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Kruemmelspalter** [TareqAlqutami/rtmp-hls-server#15]
Using Docker Compose:
```
version: "3"

services:
  rtmp-server:
    image: alqutami/rtmp-hls
    ports:
      - "13080:80"
      - "1935:1935"
```
so it looks like some file doesn't have `x` (execute) permission
running on Raspberry Pi 4 (ARM); Hypriot OS

**Comment by Kruemmelspalter** [comment]
Maybe it's because this is for amd64 not for arm(/v7)
Also tried building on RasPi but no luck

**Comment by petaren** [comment]
@Kruemmelspalter I had the same issue but managed to get it to work. I'm using Balena for my rPi and by just specifying the image it pulled a compiled x86 version that didn't work. If I however downloaded the repo and built it from there, then it works. 

```
  rtmp:
    build: ./rtmp
    # image: alqutami/rtmp-hls:latest-alpine
    ports:
      - "1935:1935"
      - "8080:8080"
```

Essentially, I went from the commented out line referring to the image, to the line specifying a folder to build from. When using Balena, it builds in their cloud and deploys to my rPi. Not sure how Hypriot OS works.
